'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { useRouter, useSearchParams } from 'next/navigation'

export default function ResetPasswordPage() {
  const [password, setPassword] = useState('')
    const [confirmPassword, setConfirmPassword] = useState('')
      const [loading, setLoading] = useState(false)
        const [message, setMessage] = useState<string | null>(null)
          const [error, setError] = useState<string | null>(null)
            const [tokenError, setTokenError] = useState(false)
            
              const router = useRouter()
                const searchParams = useSearchParams()
                  const supabase = createClient()
                  
                    useEffect(() => {
                        // Verificar se existe um token de recuperação de senha válido
                            const verifyToken = async () => {
                                  const { data, error } = await supabase.auth.getSession()
                                        if (error || !data.session?.user) {
                                                setTokenError(true)
                                                      }
                                                          }
                                                          
                                                              verifyToken()
                                                                }, [supabase.auth])
                                                                
                                                                  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
                                                                      e.preventDefault()
                                                                          setLoading(true)
                                                                              setError(null)
                                                                                  setMessage(null)
                                                                                  
                                                                                      // Validações
                                                                                          if (!password || !confirmPassword) {
                                                                                                setError('Por favor, preencha todos os campos.')
                                                                                                      setLoading(false)
                                                                                                            return
                                                                                                                }
                                                                                                                
                                                                                                                    if (password.length < 8) {
                                                                                                                          setError('A senha deve ter pelo menos 8 caracteres.')
                                                                                                                                setLoading(false)
                                                                                                                                      return
                                                                                                                                          }
                                                                                                                                          
                                                                                                                                              if (password !== confirmPassword) {
                                                                                                                                                    setError('As senhas não conferem.')
                                                                                                                                                          setLoading(false)
                                                                                                                                                                return
                                                                                                                                                                    }
                                                                                                                                                                    
                                                                                                                                                                        try {
                                                                                                                                                                              const { error } = await supabase.auth.updateUser({
                                                                                                                                                                                      password: password,
                                                                                                                                                                                            })
                                                                                                                                                                                            
                                                                                                                                                                                                  if (error) throw error
                                                                                                                                                                                                  
                                                                                                                                                                                                        setMessage('Senha redefinida com sucesso! Redirecionando para o login...')
                                                                                                                                                                                                              setTimeout(() => {
                                                                                                                                                                                                                      router.push('/login')
                                                                                                                                                                                                                            }, 2000)
                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                      setError(err instanceof Error ? err.message : 'Erro ao redefinir a senha.')
                                                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                                                setLoading(false)
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                        if (tokenError) {
                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                  <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-dark-bg px-4">
                                                                                                                                                                                                                                                                          <div className="w-full max-w-md rounded-2xl border border-slate-200 dark:border-white/10 bg-white dark:bg-dark-card p-8 shadow-xl">
                                                                                                                                                                                                                                                                                    <h1 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">
                                                                                                                                                                                                                                                                                                Link Inválido
                                                                                                                                                                                                                                                                                                          </h1>
                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-slate-500 dark:text-slate-400 mb-6">
                                                                                                                                                                                                                                                                                                                                Este link de recuperação de senha expirou ou é inválido. Por favor, solicite um novo link.
                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                    <div className="mt-6 text-sm text-center">
                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                              href="/auth/forgot-password"
                                                                                                                                                                                                                                                                                                                                                                                            className="inline-block px-4 py-2 rounded-xl bg-primary-600 hover:bg-primary-500 text-white font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                      Solicitar novo link
                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-dark-bg px-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="w-full max-w-md rounded-2xl border border-slate-200 dark:border-white/10 bg-white dark:bg-dark-card p-8 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Redefinir Senha
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-slate-500 dark:text-slate-400 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Digite uma nova senha para sua conta.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            htmlFor="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Nova Senha
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="block w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50 px-3 py-2.5 text-slate-900 dark:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Mínimo 8 caracteres"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        htmlFor="confirmPassword"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Confirmar Senha
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id="confirmPassword"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={confirmPassword}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setConfirmPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="block w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50 px-3 py-2.5 text-slate-900 dark:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Repita a nova senha"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-green-600 dark:text-green-400">{message}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-xl bg-primary-600 hover:bg-primary-500 disabled:opacity-50 text-white py-3 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? 'Redefinindo...' : 'Redefinir Senha'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-6 text-sm text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/login" className="text-primary-600 hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Voltar para o login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }'